DevSnowflake/code-examples

JavaScript/odd-even.js
Added odd or even example.
Returns in the console if the number is odd or even.
=> feat(JavaScript): add odd-or-even example.

JavaScript/fetch-get-request-with-auth.js
Fetch request example with Authorization header.
=> feat(JS): Add fetch-get-request-with-auth example.

JavaScript/fetch-get-request.js
Normal fetch GET API request with Authorization header.
=> feat(JS): Added fetch-get-rquest.js.

Nodejs/Node-Fetch/fetch-get-request.js
I forgot to remove the old code in my previous PR, sorry :sweat_smile:
=> fix (JavaScript): Remove old code.

Go/insertion-sort.go
=> add insertion sort golang

JavaScript/anagram.js
Added an interesting Anagram problem for JavaScript language in a file named `anagram.js`
=> JavaScript: Added Anagram program

TypeScript/mongoose-model.ts
Added example mongodb scheme using Mongoose.
=> feat(TypeScript): Example mongoose schema.

Nodejs/Mongoose/mongoose-model.js
Added example mongodb scheme using Mongoose (JavaScript version).
=> feat(JS): Added mongoose model example.

C#/marquee.cs
=> feat(C#): create ASCII marquee animation

Python/sortArray_of_0,s_1,s_2,s.py, Python/sortArrayof_0,s_1,s_2,s.py
=> sortArray_of_0,s_1,s_2,s.py

C/winhttps.c
Create a C file that sends a simple, plain HTTP/HTTPS request. This source only works on Windows because it utilizes the Windows API to send requests.
Tested with MinGW and Visual C++ (Visual Studio).
=> feat(C): add winhttps.c

C/reverse_a_string.c
=> Added reverse a string in C

C++/asc_space.cpp
the file is present in C++ asc_space.cpp
=> asc_space.cpp file is added..

JavaScript/optional-chaining.js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
=> feat(JavaScript): Optional chaining

JavaScript/anagram.js
I deleted the unwanted line of code :P
=> JavaScript: Anagram Program Fix

C++/string_to_int.cpp
Program That converts a string to an integer using Recursion
=> added String to Number program

Python/chatbot/LICENSE, Python/chatbot/README.md, Python/chatbot/ext/__init__.py, Python/chatbot/ext/chatbot.py, Python/chatbot/ext/font.py, Python/chatbot/ext/start.py, Python/chatbot/ext/user.py, Python/chatbot/main.py
A simple chatbot made in python.
*It can generate fake user info along with some fancy fonts too.*
=> Chatbot : Python

TypeScript/next-tailwind-themeswitcher/components/ThemeSwitcher.tsx, TypeScript/next-tailwind-themeswitcher/pages/_app.tsx, TypeScript/next-tailwind-themeswitcher/pages/index.tsx
Quick update:
- Added comments to ThemeSwitcher.tsx to help viewers understand what's going on in the code.
- Formatted + removed unnecessary div in index.tsx.
=> refactor(TS/next-tailwind-themeswitcher): Formatted code and added comments to themeswitcher.tsx.

TypeScript/next-tailwind-themeswitcher/package.json
Added important devDependencie "TypeScript".
=> fix(TS/next-tailwind-themeswitcher): Added important package.

Python/Calculator.py
I have written a python code for performing mathematical calculations like addition, subtraction, multiplication, division and modulo.
=> Python Code for a Simple Calculator

Java/tic_tac_toe.java
removed LOTS of unnecessary if statements and other small tweaks to `tic_tac_toe.java`
=> refactor(Java/tic_tac_toe.java): shorten several functions

Python/budapest_buslist.py
listing all public transport vehicles all across budapest
=> python program budapest_buslist added

Nodejs/DiscordJS-Interactions/README.md, Nodejs/DiscordJS-Interactions/config.js, Nodejs/DiscordJS-Interactions/index.js, Nodejs/DiscordJS-Interactions/package.json, Nodejs/DiscordJS-Interactions/src/commands/avatar.js, Nodejs/DiscordJS-Interactions/src/commands/userinfo.js, Nodejs/DiscordJS-Interactions/src/lib/setup.js, Nodejs/DiscordJS-Interactions/src/listeners/interactionCreate.js, Nodejs/DiscordJS-Interactions/src/listeners/ready.js
This code has context menus and slash commands, buttons have been used aswell.
=> Add DiscordJS Interaction Bot

Brainfuck/hello_world.bf
Added 2 methods of printing "Hello World!" in Brainfuck in 2 styles: Properly brainfucky (everything on one line) and kinda readable (not putting everything on one line and added an explanation of what each line does)
=> Added multiple methods of printing "Hello World" in Brainfuck

Solidity/HelloWorld.sol
Added solidity file and first HelloWorld script ☺️
Hope the other share a concern solidity project
=> add solidity file and first HelloWorld script

JavaScript/odd-even.js
use `%` operator to check if a number is even or odd, instead of `Number.isInteger`.
=> refactor(JavaScript/odd-even.js): use `%` operator

Python/RemoveHtmlTags.py
A function that can be used to remove html tags from a string (if any).
=> Added RemoveHtmlTags (Python)

C++/Palindrome.cpp
Added C++ code to check if an entered no is Palindrome or not.
=> Feat(C++): Palindrome Number

Python/bubble_sort.py
=> Add bubble sort algorithm in Python

C++/Reverse the array.cpp
**Added Reverse-the-array-program. Hope it will help. DO ACCEPT MY PR.**
=> Reverse a Array Program

C++/matrix.cpp, Python/FaceDetection.py
Please accept my Pull Request..
=> (CPP) Matrix

JavaScript/median.js
Function to find median of an array of numbers.
**Extra information:**
=> feat(JavaScript): find median function

JavaScript/quickSort.js
Implementation of quick sort algorithm in JavaScript
=> Quick sort algorithm

TypeScript/index-signature.ts
demonstrate use of index signatures in typescript
=> index signatures in TS

C/reverse_a_string.c
In Windows builds, there is already a built-in `strrev()` function. See https://www.geeksforgeeks.org/strrev-function-in-c/ for details
=> refactor(C/reverse_a_string.c): use `strrev()`

Python/PasswordGen.py
=> refactor(Python/PasswordGen.py): rewrite `PasswordGen.py`

Kotlin/datatypes.kt
A small kotlin program on data types
=> data types in kotlin

Dart/even_odd.dart
=> even and odd

Java/ATM.java
=> java program

Java/LinkedListApp.java
I implemented linked list algo in Java language. Please check and accept my PR.
=> implemented linked list algorithm in Java

SciLab/hello_world.sci
Added hello world program for SciLab
=> Added SciLab

MATLAB/hello_world.m
Added hello world program for MATLAB
=> Added MATLAB

Java/QueueArrayApp.java
This is queuearrayapp implement by java.
=> QueueArrayApp

Java/Cyclic.java
Kindly merge my Cyclic sort Java program. Thank you and have a nice day.
=> Added a Cyclic Sort Java Program

JavaScript/binary-search-tree.js
Things covered in this pr: 
Added a javascript class for Binary Search Tree which provides following functionality: 
- Create ( create instance of Binary Search Tree )
- Insert
- Delete
- Includes
- Number of nodes
- Is valid BST
- Display
- Traversals ( inorder, preorder, postorder )
=> :sparkles: Added binary search tree javascript class

JavaScript/weather-app/index.html, JavaScript/weather-app/weather-api.js
This is a simple weather application that can be scaled using different URL parameters and the API can be obtained from the given link in the code itself.
=> Weather application

Nodejs/youtube-video-download.js
Adding support for playlist, progress bar.
=> feat(NodeJS): youtube-video-download

JavaScript/avg-of-arrays.js
JavaScript function to find the average of all integers in a given array
=> Avg of arrays js

codes/V/hello-world.v
ignore the typo in the commit message
=> feat(V): added V programming language

codes/JavaScript/web-scraping.js
Might add more sites to the examples later, it is actually kinda difficult to find sites that are scrapable and aren't just shopping sites
=> Showing off basics of web scraping in JS

codes/Nodejs/discord-sliders-1.1.3/LICENSE, codes/Nodejs/discord-sliders-1.1.3/README.md, codes/Nodejs/discord-sliders-1.1.3/index.js, codes/Nodejs/discord-sliders-1.1.3/package-lock.json, codes/Nodejs/discord-sliders-1.1.3/package.json
Uploaded source code of discord-sliders v1.1.3.
» Main repository of this package: https://github.com/Deadr3amer/discord-sliders
=> Add source code of discord-sliders project.

codes/C++/SelectionSort.cpp
I have added selctionsort code in cpp
=> feat: Added Selectionsort
